### PR TITLE
fix redefined property 'lineWidth'

### PR DESCRIPTION
**Pull request by wusuopu**

### CODE REVIEW

**Comment by wusuopu** [comment]
It occur a error when running the program.

simulator screen shot apr 18 2016 11 05 44 am

**Comment by Jpadilla1** [comment]
Hi, can you go into more detail on why the removal of the `lineWidth` property? I see the property in the iOS Charts library just fine https://github.com/danielgindi/Charts/blob/v2.2.3/Charts/Classes/Data/Interfaces/ILineRadarChartDataSet.swift#L38 

Can you also tell me how to reproduce the error? Thanks.

**Comment by wusuopu** [comment]
@Jpadilla1 because the `lineWidth` property has redefined.
see
https://github.com/crowdsdom/react-native-ios-charts/blob/master/components/CombinedChart.js#L34
https://github.com/crowdsdom/react-native-ios-charts/blob/master/components/CombinedChart.js#L52

and 
https://github.com/crowdsdom/react-native-ios-charts/blob/master/components/LineChart.js#L34
https://github.com/crowdsdom/react-native-ios-charts/blob/master/components/LineChart.js#L52

**Comment by Jpadilla1** [comment]
Ah now I see! Sorry I didn't see that xD Thank you! :)

**Pull request merged**
