### PR TITLE
Implemented BalloonMarker Support

### PR DESCRIPTION
**Pull request by cesardeazevedo**
Related to #6 

I also added markers on Line and Radar examples...

### CODE REVIEW

**Comment by cesardeazevedo** [comment]
**Edit:** i committed a wrong file, i had reset the commit.

**Comment by Jpadilla1** [comment]
Hi @cesardeazevedo your PR looks good. But I just merged the swift 3 support branch and looks like it caused a couple of conflicts. Also, can you update the instances of `isExists` to `exists` (new version of SwiftyJson) and then I can happily merge!

Thanks for your contribution! :)

**Comment by cesardeazevedo** [comment]
Cool, i'll update my pull request soon.

**Comment by cesardeazevedo** [comment]
It's done!

**Pull request merged**
